const status = {
  WARNING: "WARNING",
  SUCCESS: "SUCCESS",
};
const modalID = {
  DELETE_PRODUCT: "DELETE_PRODUCT",
  NAVIGATE_TO_LOGIN: "NAVIGATE_TO_LOGIN",
  NAVIGATE_TO_HOMEPAGE: "NAVIGATE_TO_HOMEPAGE",
};
export const CONSTANTS = {
  status,
  modalID,
};
